###############################################################################
# Copyright (c) 2018 Kevin Palfreyman
###############################################################################

#To set the default log file and level for an EPL package, monitor, or event, specify
# logging details in the eplLogging section of the YAML configuration file.
#For example:
#eplLogging:
#  com.myCompany.Client:
#    file: apama/Client.log
#    level: DEBUG
#  com.myCompany.Internal: { level: ERROR }


#See the information on setting log files and log levels in a YAML configuration file in the documentation for more
# information about the supported options.
#To enable use of this file when you launch this project from Designer, edit the project's run/launch configuration,
#open the correlator, and tick the "Configuration" checkbox next to the textbox that names this .yaml file.

  
eplPlugins:
  SenseHat_HelloWorldPlugin:
    pythonFile: "${PARENT_DIR}/../plugins/SenseHat_HelloWorld_Plugin.py"
    class: SenseHatHelloWorldClass
